# Generated by Django 6.0.5 on 2026-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('education', 'Education'), ('internship', 'Internship'), ('certification', 'Certification'), ('milestone', 'Milestone/Achievement')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working/studying here', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Describe roles, tasks or curriculum. Separate bullet points with newlines.')),
                ('media_asset', models.ImageField(blank=True, help_text='Image/Certificate upload if applicable', null=True, upload_to='experiences/')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(help_text='Upload your image or video showcase file', upload_to='gallery/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('category', models.CharField(choices=[('memories', 'Memories'), ('work', 'Work Moments'), ('achievements', 'Achievements')], default='memories', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Media Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai_ml', 'AI / ML / Tools'), ('core', 'Core / Soft Skills')], max_length=20)),
                ('icon_svg', models.TextField(blank=True, help_text='Raw SVG XML or Tailwind/FontAwesome icon class name.', null=True)),
                ('proficiency', models.IntegerField(default=80, help_text='Skill percentage between 0 and 100')),
                ('orbit_distance', models.IntegerField(default=150, help_text='Radius distance in skill galaxy orbit')),
                ('orbit_speed', models.FloatField(default=1.0, help_text='Speed factor of orbiting animation')),
            ],
            options={
                'ordering': ['category', '-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('project_worked_on', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
